CREATE ROLE platform WITH LOGIN PASSWORD 'Passw0rd!';

GRANT USAGE ON SCHEMA platform, events, ai, logs TO platform;
GRANT CREATE ON SCHEMA platform, events, ai, logs TO platform;

ALTER DEFAULT PRIVILEGES IN SCHEMA events GRANT ALL ON TABLES TO platform;
ALTER DEFAULT PRIVILEGES IN SCHEMA ai GRANT ALL ON TABLES TO platform;